using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JPG_Viewer
{
    enum EXIFMetadataEnum // Нужно присвоить каждому из свойств Exif и TIFF соответствующий двухбайтный маркер
    {
        ExposureTime = 0x829A,
        FNumber = 0x829D,
        ExposureProgram = 0x8822,
        SpectralSensitivity = 0x8824,
        OECF = 0x8828,
        ISOSpeed = 0x8833,
        ExifVersion = 0x9000,
        DateTimeOriginal = 0x9003,
        DateTimeDigitized = 0x9004,
        ComponentsConfiguration = 0x9101,
        CompressedBitsPerPixel = 0x9102,
        ShutterSpeedValue = 0x9201,
        ApertureValue = 0x9202,
        BrightnessValue = 0x9203,
        ExposureBiasValue = 0x9204,
        MaxApertureValue = 0x9205,
        SubjectDistance = 0x9206,
        MeteringMode = 0x9207,
        LightSource = 0x9208,
        Flash = 0x9209,
        FocalLength = 0x920A,
        SubjectArea = 0x9203,
        MakerNote = 0x927C,
        UserComment = 0x9286,
        SubsecTime = 0x9290,
        SubsecTimeOriginal = 0x9291,
        SubsecTimeDigitized = 0x9292,
        FlashpixVersion = 0xA000,
        ColorSpace = 0xA001,
        PixelXDimension = 0xA002,
        PixelYDimension = 0xA003,
        RelatedSoundFile = 0xA004,
        InteroperabilityIFDPointer, // @TODO
        FlashEnergy,
        SpatialFrequencyResponse,
        FocalPlaneXResolution,
        FocalPlaneYResolution,
        FocalPlaneResolutionUnit,
        SubjectLocation,
        ExposureIndex,
        SensingMethod,
        FileSource,
        SceneType,
        CFAPattern,
        CustomRendered,
        ExposureMode,
        WhiteBalance,
        DigitalZoomRation,
        FocalLengthIn35mmFilm,
        SceneCaptureType,
        GainControl,
        Contrast,
        Saturation,
        Sharpness,
        DeviceSettingDescription,
        SubjectDistanceRange,
        ImageUniqueID
    }
    enum TIFFMetadataEnum
    {
        ImageWidth                          = 0x0100,
        ImageHeight                         = 0x0101,
        BitsPerSample                       = 0x0102,
        Compression                         = 0x0103,
        PhotometricInterpretation           = 0x0106,
        ImageDescription                    = 0x010E,
        Make                                = 0x010F,
        Model                               = 0x0110,
        StripOffsets                        = 0x0111,
        Orientation                         = 0x0112,
        SamplesPerPixel                     = 0x0115,
        RowsPerStrip                        = 0x0116,
        StripByteCounts                     = 0x0117,
        XResolution                         = 0x011A,
        YResolution                         = 0x011B,
        PlanarConfiguration                 = 0x011C,
        ResolutionUnit                      = 0x0128,
        TransferFunction                    = 0x012D,
        Software                            = 0x0131,
        DateTime                            = 0x0132,
        Artist                              = 0x013B,
        WhitePoint                          = 0x013E,
        PrimaryChromaticities               = 0x013F,
        JPEGInterchangeFormat               = 0x0201,
        JPEGInterchangeFormatLength         = 0x0202,
        YCbCrCoefficients                   = 0x0211,
        YCbCrSubSampling                    = 0x0212,
        YCbCrPositioning                    = 0x0213,
        ReferenceBlackWhite                 = 0x0214,
        Copyright                           = 0x8298,
        ExifIFDPointer                      = 0x8769,
        GPSInfoIFDPointer                   = 0x8825,
        InteroperabilityIFDPointer          = 0xA005,
    }
}
