BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "favorite_jpeg_images" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"image_name_id"	INTEGER NOT NULL,
	"image_path_id"	INTEGER NOT NULL,
	"image_author_id"	INTEGER NOT NULL,
	"device_creator_id"	INTEGER NOT NULL,
	"image_datetime"	TEXT,
	FOREIGN KEY("image_name_id") REFERENCES "image_names"("ID"),
	FOREIGN KEY("image_author_id") REFERENCES "image_authors"("ID"),
	FOREIGN KEY("image_path_id") REFERENCES "image_paths"("ID"),
	FOREIGN KEY("device_creator_id") REFERENCES "devices"("ID")
);
CREATE TABLE IF NOT EXISTS "devices" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"device_name"	TEXT
);
CREATE TABLE IF NOT EXISTS "image_authors" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"author"	TEXT
);
CREATE TABLE IF NOT EXISTS "image_paths" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"path"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "image_names" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"image_name"	TEXT NOT NULL
);
INSERT INTO "devices" VALUES (1,NULL);
INSERT INTO "image_authors" VALUES (1,NULL);
COMMIT;
